#############################################
# .gitlab-ci.infra.yml
#############################################

infra:
  stage: infra
  image:
    name: hashicorp/terraform:1.3.9
    entrypoint: [""]
  script:
    - echo "=== Terraform init/plan/apply for Infra ==="
    - cd services/predict-model/terraform
    - terraform init
    - terraform plan -out=tfplan
    - terraform apply -auto-approve tfplan
    - echo "=== Terraform Outputs ==="
    - terraform output
  artifacts:
    paths:
      - services/predict-model/terraform/terraform.tfstate
    expire_in: 1 week
  only:
    - infra
