#############################################
# .gitlab-ci.build-deploy.yml
#############################################
build-docker:
  stage: build
  image: docker:20.10.16
  services:
    - docker:dind
  variables:
    DOCKER_HOST: "tcp://docker:2375/"
  script:
    - apk update && apk add --no-cache python3 py3-pip
    - pip install awscli
    - echo "=== Build & push Django container ==="
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ECR_REGISTRY
    - cd services/predict-model/Django
    - docker build -t django-crypto:latest .
    - docker tag django-crypto:latest $AWS_ECR_REGISTRY/django-crypto:latest
    - docker push $AWS_ECR_REGISTRY/django-crypto:latest
    - cd ../../..
    - echo "=== Build & push Streamlit container ==="
    - cd services/predict-model/streamlit
    - docker build -t streamlit-crypto:latest .
    - docker tag streamlit-crypto:latest $AWS_ECR_REGISTRY/streamlit-crypto:latest
    - docker push $AWS_ECR_REGISTRY/streamlit-crypto:latest
    - cd ../../..
  only:
    - main

deploy:
  stage: deploy
  image:
    name: juliencourteville/aws-kube:latest
    entrypoint: [""]
  script:
    - echo "=== Update kubeconfig for EKS (MyEKS) ==="
    - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name myekscrypto
    - sed -i "s|\${STREAMLIT_ALB_URL}|$STREAMLIT_ALB_URL|g" services/predict-model/k8s/configmap.yaml
    - echo "=== Deploy Kubernetes manifests ==="
    - kubectl apply -f services/predict-model/k8s/
    - echo "=== Restart Django deployment ==="
    - kubectl rollout restart deployment django-deployment
    - kubectl get pods
  dependencies:
    - build-docker
  only:
    - main
