stages:
  - build
  - deploy
  - infra

include:
  - local: '.gitlab-ci.build-deploy.yml'
  - local: '.gitlab-ci.infra.yml'

infra_job:
  stage: infra
  script:
    - echo "Lancement du job d'infrastructure"
  rules:
    - if: '$CI_COMMIT_BRANCH == "infra"'
      when: always
    - when: never

build_deploy_job:
  stage: build
  script:
    - echo "Lancement du job build & deploy"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never
deploy_job:
  stage: deploy
  script:
    - echo "Lancement du job deploy"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never
