apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  # Base de données RDS
  DB_HOST: "dbcrypto.cvrhlcdjhuda.eu-west-3.rds.amazonaws.com"
  DB_NAME: "postgres"
  DB_PORT: "5432"

  # URL de Streamlit (placeholder à mettre à jour après création de l'ALB)
  STREAMLIT_URL: "http://k8s-default-cryptoin-34db866180-1481508178.eu-west-3.elb.amazonaws.com/streamlit"

