apiVersion: apps/v1
kind: Deployment
metadata:
  name: predict-model-deployment
  namespace: data-processing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: predict-model
  template:
    metadata:
      labels:
        app: predict-model
    spec:
      containers:
      - name: predict-model
        image: "{{ .Values.image.repository }}/predict-model:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8000
        env:
        - name: MODEL_PATH
          value: "/app/model/model.joblib"  # VARIABLE : Chemin du modèle (ajuster si nécessaire)
      restartPolicy: Always

