apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "password"

  # Si tu veux y mettre la SECRET_KEY Django (optionnel)
  # DJANGO_SECRET_KEY: "super-secret-key"

