apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit-container
        # => Repo "streamlit-crypto"
        image: 131674823919.dkr.ecr.eu-west-3.amazonaws.com/streamlit-crypto:latest

        ports:
          - containerPort: 8501

