apiVersion: batch/v1
kind: Job
metadata:
  name: extract-data-job
  namespace: data-processing
spec:
  template:
    spec:
      containers:
      - name: extract-data
        image: [your-aws-ecr-repo]/extract-data:latest  # Cette image doit être définie une fois que ton Dockerfile est construit
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials   # Nom du secret à utiliser (référence à secret.yaml)
              key: access_key_id      # Clé spécifique dans le secret
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials   # Nom du secret à utiliser
              key: secret_access_key  # Clé spécifique dans le secret
        - name: DATA_SOURCE_URL
          value: "http://data-service/data"   # Exemple, cette valeur est "variable" et pourrait être modifiée selon tes besoins.
        - name: OUTPUT_S3_BUCKET
          value: "s3://my-bucket/data"  # Exemple, cela peut changer en fonction de l'environnement et des besoins
      restartPolicy: Never
  backoffLimit: 4

