apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials   # Nom du secret, utilisé dans d'autres fichiers pour y accéder
  namespace: data-processing   # Namespace où le secret sera disponible
type: Opaque
data:
  access_key_id: BASE64_ENCODED_ACCESS_KEY_ID      # Remplacer par la valeur encodée en Base64
  secret_access_key: BASE64_ENCODED_SECRET_ACCESS_KEY  # Remplacer par la valeur encodée en Base64
#echo -n "acces-key" | base64
