stages:
  - build
  - push
  - deploy

variables:
  AWS_DEFAULT_REGION: "eu-west-1"
  IMAGE_NAME: "[your-aws-ecr-repo]/extract-data"

before_script:
  # Installer les outils nécessaires
  - apk add --no-cache curl jq python3 py3-pip docker-cli
  - pip install --no-cache-dir awscli

build:
  stage: build
  script:
    # Construire l'image Docker à partir du Dockerfile
    - docker build -t $IMAGE_NAME .

push:
  stage: push
  script:
    # Se connecter à ECR et pousser l'image
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $IMAGE_NAME
    - docker push $IMAGE_NAME

deploy:
  stage: deploy
  script:
    # Déployer sur Kubernetes
    - kubectl apply -f k8s/job.yaml

